<div ng-app="wpchatbull" class="wrap" ng-controller="SettinsController" ng-cloak>
    <h1><?php _e("ChatBull Settings", $this->plugin_domain); ?></h1>    
    <p><?php _e("Thank you for using <a href='http://chatbull.in' target='_new'>ChatBull</a>. Please rate us on <a href='https://wordpress.org/support/plugin/wp-chatbull/reviews/' target='_blank'>WordPress.org</a>.", $this->plugin_domain) ?></p>

    <div class="updated settings-error notice" ng-show="notification.message"> 
        <div ng-bind-html="notification.message"></div>
    </div>

    <div class="error notice" ng-show="notification.errors">
        <div ng-bind-html="notification.errors"></div>
    </div>

    <form name="cbsetting_form" method="post" novalidate="novalidate" ng-submit="cbsetting_form.$valid && save_settings()">
        <input name="action" value="update" type="hidden">
        <input id="_wpnonce" name="_wpnonce" value="<?php echo wp_create_nonce('wporg_frontend_delete'); ?>" type="hidden">
        <?php wp_referer_field(true) ?>

        <table class="form-table">
            <tbody>
                <tr>
                    <th scope="row"><label><?php _e("Chatbox Widget Method", $this->plugin_domain) ?> : </label></th>
                    <td>
                        <label for="gaxon_wpcbcp_chatbox_method-2"><input name="gaxon_wpcbcp_chatbox_method" id="gaxon_wpcbcp_chatbox_method-2" ng-model="settings.gaxon_wpcbcp_chatbox_method" value="install-plugin" type="radio"> <span><?php _e("Setup ChatBull", $this->plugin_domain); ?></span></label>
                        <label for="gaxon_wpcbcp_chatbox_method-1"><input name="gaxon_wpcbcp_chatbox_method" id="gaxon_wpcbcp_chatbox_method-1" ng-model="settings.gaxon_wpcbcp_chatbox_method" value="widget-code" type="radio"> <span><?php _e("Enter Widget Code", $this->plugin_domain); ?></span></label><br>
                        <p class="description" id="gaxon_wpcbcp_pick_wpuser-description"><?php _e("Choose an option to setup chatbox and configuration.", $this->plugin_domain) ?></p>
                    </td>
                </tr>

                <tr ng-show="settings.gaxon_wpcbcp_chatbox_method == 'widget-code'">
                    <th scope="row"><label for="gaxon_wpcbcp_chatbull_dir"><?php _e("Chatbox Widget Code", $this->plugin_domain) ?> : </label></th>
                    <td>
                        <div class="input-group">
                            <textarea name="gaxon_wpcbcp_widget_code" rows="5" cols="80" id="gaxon_wpcbcp_widget_code" class="medium-text code wpcbcp-form-control" ng-model="settings.gaxon_wpcbcp_widget_code" ng-required="settings.gaxon_wpcbcp_chatbox_method == 'widget-code'"></textarea>
                        </div>

                        <div class="wpcbcp-error" ng-show="(cbsetting_form.$submitted || cbsetting_form.gaxon_wpcbcp_widget_code.$touched) && cbsetting_form.gaxon_wpcbcp_widget_code.$invalid">
                            <p ng-show="cbsetting_form.gaxon_wpcbcp_widget_code.$error.required"><?php _e('This field is required.', $this->plugin_domain); ?></p>
                        </div>
                        <p class="help" id="gaxon_wpcbcp_chatbull_dir-description"><?php _e("Enter Chatbox Widget code generated by <a title='ChatBull plugin' href='http://chatbull.in' target='_new'>ChatBull</a> plugin.", $this->plugin_domain) ?></p>
                    </td>
                </tr>

                <tr ng-show="settings.gaxon_wpcbcp_chatbox_method == 'install-plugin'">
                    <th scope="row"><label for="gaxon_wpcbcp_chatbull_dir"><?php _e("Chatbull Directory", $this->plugin_domain) ?> : </label></th>
                    <td>
                        <div class="input-group">
                            <input type="text" id="gaxon_wpcbcp_chatbull_dir" name="gaxon_wpcbcp_chatbull_dir" ng-model="settings.gaxon_wpcbcp_chatbull_dir" ng-disabled="settings.gaxon_wpcbcp_linked == 'yes' && !change_plugin_path" class="regular-text wpcbcp-form-control" ng-required="settings.gaxon_wpcbcp_chatbox_method == 'install-plugin'">
                            <button ng-show="(settings.gaxon_wpcbcp_chatbull_dir && settings.gaxon_wpcbcp_linked == 'no') || change_plugin_path" ng-click="install_plugin($event)" class="wpcbcp-form-action" type="button">{{labels.install}}</button>
                            <button ng-show="(settings.gaxon_wpcbcp_chatbull_dir && settings.gaxon_wpcbcp_linked == 'no') || change_plugin_path" ng-click="check_n_save($event)" class="wpcbcp-form-action" type="button">{{labels.check_n_save}}</button>
                            <button ng-show="settings.gaxon_wpcbcp_chatbull_dir && settings.gaxon_wpcbcp_linked == 'yes' && !change_plugin_path" ng-click="chack_status($event)" class="wpcbcp-form-action" type="button">{{labels.chack_status}}</button>
                            <button ng-show="settings.gaxon_wpcbcp_chatbull_dir && settings.gaxon_wpcbcp_linked == 'yes' && !change_plugin_path" ng-click="change_plugin_path = true" class="wpcbcp-form-action" type="button">{{labels.change}}</button>
                        </div>

                        <div class="wpcbcp-error" ng-show="(cbsetting_form.$submitted || cbsetting_form.gaxon_wpcbcp_chatbull_dir.$touched) && cbsetting_form.gaxon_wpcbcp_chatbull_dir.$invalid">
                            <p ng-show="cbsetting_form.gaxon_wpcbcp_chatbull_dir.$error.required"><?php _e('This field is required.', $this->plugin_domain); ?></p>
                        </div>
                        <p class="help" id="gaxon_wpcbcp_chatbull_dir-description"><?php _e("Ex: " . site_url('/'), $this->plugin_domain) ?>{{settings.gaxon_wpcbcp_chatbull_dir}}</p>
                        <p ng-show="settings.gaxon_wpcbcp_linked == 'yes' && !change_plugin_path"><?php _e('To change ChatBull settings <a href="'.site_url('/{{settings.gaxon_wpcbcp_chatbull_dir}}').'" target="_new">click here</a> .', $this->plugin_domain) ?></p>
                    </td>
                </tr>

                <tr>
                    <th scope="row"><label for="gaxon_wpcbcp_enabled_chatbox"><?php _e("Show Chat Window", $this->plugin_domain) ?> : </label></th>
                    <td>
                        <select id='gaxon_wpcbcp_enabled_chatbox' name='gaxon_wpcbcp_enabled_chatbox' ng-model="settings.gaxon_wpcbcp_enabled_chatbox" class="regular-text wpcbcp-form-control" required>
                            <option value="yes"><?php _e("Yes", $this->plugin_domain); ?></option>
                            <option value="no"><?php _e("No", $this->plugin_domain); ?></option>
                        </select>
                        <div class="wpcbcp-error" ng-show="(cbsetting_form.$submitted || cbsetting_form.gaxon_wpcbcp_enabled_chatbox.$touched) && cbsetting_form.gaxon_wpcbcp_enabled_chatbox.$invalid">
                            <p ng-show="cbsetting_form.gaxon_wpcbcp_enabled_chatbox.$error.required"><?php _e('This field is required.', $this->plugin_domain); ?></p>
                        </div>
                        <p class="description" id="gaxon_wpcbcp_enabled_chatbox-description"><?php _e("Show Hide Chat Window.", $this->plugin_domain) ?></p>
                    </td>
                </tr>

                <tr>
                    <th scope="row"><label for="gaxon_wpcbcp_pick_wpuser"><?php _e("Pick Logged-in User", $this->plugin_domain) ?> : </label></th>
                    <td>
                        <label for="gaxon_wpcbcp_pick_wpuser"><input name="gaxon_wpcbcp_pick_wpuser" id="gaxon_wpcbcp_pick_wpuser" ng-model="settings.gaxon_wpcbcp_pick_wpuser" ng-true-value="'yes'" ng-false-value="'no'" type="checkbox"> <?php _e("Yes", $this->plugin_domain); ?></label>
                        <p class="description" id="gaxon_wpcbcp_pick_wpuser-description"><?php _e("User's email and name will be entered by default in chat window open.", $this->plugin_domain) ?></p>
                    </td>
                </tr>

                <tr>
                    <th scope="row"><label for="gaxon_wpcbcp_visiblity_tpe"><?php _e("Show Hide on pages", $this->plugin_domain) ?> : </label></th>
                    <td>
                        <select id='gaxon_wpcbcp_visiblity_tpe' name='gaxon_wpcbcp_visiblity_tpe' ng-model="settings.gaxon_wpcbcp_visiblity_tpe" class="regular-text wpcbcp-form-control" required>
                            <option value="all"><?php _e("Show on all pages", $this->plugin_domain); ?></option>
                            <option value="show_on_selected"><?php _e("Show on selected pages", $this->plugin_domain); ?></option>
                            <option value="hide_on_selected"><?php _e("Hide on selected pages", $this->plugin_domain); ?></option>
                        </select>
                        <div class="wpcbcp-error" ng-show="(cbsetting_form.$submitted || cbsetting_form.gaxon_wpcbcp_visiblity_tpe.$touched) && cbsetting_form.gaxon_wpcbcp_visiblity_tpe.$invalid">
                            <p ng-show="cbsetting_form.gaxon_wpcbcp_visiblity_tpe.$error.required"><?php _e('This field is required.', $this->plugin_domain); ?></p>
                        </div>
                        <p class="description" id="gaxon_wpcbcp_visiblity_tpe-description"><?php _e("Manage chat window visibility.", $this->plugin_domain) ?></p>
                    </td>
                </tr>

                <?php
                $args = array(
                    'post_type' => 'page',
                    'showposts' => -1
                );
                $pages = new WP_Query($args);
                ?>

                <?php if ($pages->have_posts()): ?>
                    <tr ng-show="settings.gaxon_wpcbcp_visiblity_tpe && settings.gaxon_wpcbcp_visiblity_tpe != 'all'">
                        <th scope="row"><label for="gaxon_wpcbcp_cbwindow_pages"><?php _e("Select Pages", $this->plugin_domain) ?> : </label></th>
                        <td>
                            <select id='gaxon_wpcbcp_cbwindow_pages' name='gaxon_wpcbcp_cbwindow_pages' ng-model="settings.gaxon_wpcbcp_cbwindow_pages" class="regular-text wpcbcp-form-control" multiple>
                                <?php while ($pages->have_posts()): $pages->the_post(); ?>
                                    <?php global $post; ?>
                                    <option value="<?php echo $post->post_name; ?>" selected><?php the_title(); ?></option>
                                    <?php
                                endwhile;
                                wp_reset_postdata();
                                ?>
                            </select>
                            <div class="wpcbcp-error" ng-show="(cbsetting_form.$submitted || cbsetting_form.gaxon_wpcbcp_cbwindow_pages.$touched) && cbsetting_form.gaxon_wpcbcp_cbwindow_pages.$invalid">
                                <p ng-show="cbsetting_form.gaxon_wpcbcp_cbwindow_pages.$error.required"><?php _e('This field is required.', $this->plugin_domain); ?></p>
                            </div>
                            <p class="description" id="gaxon_wpcbcp_cbwindow_pages-description"><?php _e("Select pages to set visibility of chat window.", $this->plugin_domain) ?></p>
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
        <p class="submit"><input name="submit" id="submit" class="button button-primary" value="<?php _e("Save Settings", $this->plugin_domain); ?>" type="submit"></p>
    </form>
</div>